# Generated by Django 5.2.8 on 2025-11-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="description"),
                ),
                (
                    "demonstration",
                    models.BooleanField(default=True, verbose_name="demonstration"),
                ),
                ("author", models.CharField(max_length=50, verbose_name="author")),
            ],
        ),
    ]
