# Generated by Django 5.2.8 on 2025-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsmodel",
            name="poster",
            field=models.ImageField(
                blank=True, upload_to="main/posters/", verbose_name="poster"
            ),
        ),
    ]
