# Generated by Django 5.2.8 on 2025-11-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_projectsmodel_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsmodel",
            name="poster_2",
            field=models.ImageField(
                blank=True, upload_to="main/posters/", verbose_name="poster_2"
            ),
        ),
        migrations.AddField(
            model_name="projectsmodel",
            name="poster_3",
            field=models.ImageField(
                blank=True, upload_to="main/posters/", verbose_name="poster_3"
            ),
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="poster",
            field=models.ImageField(
                blank=True, upload_to="main/posters/", verbose_name="poster_main"
            ),
        ),
    ]
