# Generated by Django 5.2.8 on 2025-11-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_projectsmodel_poster_2_projectsmodel_poster_3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsmodel",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="project link"),
        ),
    ]
