# Generated by Django 5.2.8 on 2025-11-26 20:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_projectsmodel_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectsmodel",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AddField(
            model_name="projectsmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectsmodel",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="active"
            ),
        ),
        migrations.AddField(
            model_name="projectsmodel",
            name="order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="order"),
        ),
        migrations.AddField(
            model_name="projectsmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="author",
            field=models.CharField(max_length=100, verbose_name="author"),
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="description",
            field=models.TextField(max_length=500, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="link",
            field=models.URLField(
                blank=True,
                max_length=300,
                null=True,
                validators=[django.core.validators.URLValidator()],
                verbose_name="project link",
            ),
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="poster",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/posters/%Y/%m/",
                verbose_name="poster_main",
            ),
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="poster_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/posters/%Y/%m/",
                verbose_name="poster_2",
            ),
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="poster_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/posters/%Y/%m/",
                verbose_name="poster_3",
            ),
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="slug",
            field=models.SlugField(max_length=150, unique=True, verbose_name="slug"),
        ),
        migrations.AddIndex(
            model_name="projectsmodel",
            index=models.Index(
                fields=["is_active", "order"], name="main_projec_is_acti_92977f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectsmodel",
            index=models.Index(
                fields=["-created_at"], name="main_projec_created_371831_idx"
            ),
        ),
    ]
